# Generated by Django 5.0.7 on 2024-07-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
