# Generated by Django 5.0.7 on 2024-07-26 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0002_rifa_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerovendido',
            name='data_aquisicao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
