# Generated by Django 5.0.7 on 2024-07-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0003_numerovendido_data_aquisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='numeros_comprados',
        ),
        migrations.AddField(
            model_name='rifa',
            name='numeros',
            field=models.ManyToManyField(blank=True, null=True, related_name='numeros', to='rifa.numerovendido'),
        ),
        migrations.AlterField(
            model_name='numerovendido',
            name='data_aquisicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
