# Generated by Django 5.0.7 on 2024-07-26 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0005_alter_numerovendido_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerovendido',
            name='rifa_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa'),
        ),
    ]
