# Generated by Django 5.0.7 on 2024-07-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0006_numerovendido_rifa_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerovendido',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('V', 'Vendido'), ('R', 'Reservado')], default='D', max_length=1),
        ),
    ]
