# Generated by Django 5.0.7 on 2024-07-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('rifa', '0007_numerovendido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='numeros_ganhadores',
            field=models.ManyToManyField(blank=True, related_name='ganhadores', to='rifa.numerovendido'),
        ),
        migrations.CreateModel(
            name='VencedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifa.numerovendido')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa')),
            ],
        ),
    ]
