# Generated by Django 5.0.7 on 2024-07-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0008_rifa_numeros_ganhadores_vencedoritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='arrumado',
            field=models.BooleanField(default=False),
        ),
    ]
