# Generated by Django 5.0.7 on 2024-08-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_itemrifado'),
        ('rifa', '0009_rifa_arrumado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradelink', models.URLField(blank=True, null=True)),
                ('cotas_compradas', models.ManyToManyField(blank=True, related_name='cotas_compradas', to='rifa.rifa')),
                ('itens_ganhos', models.ManyToManyField(blank=True, related_name='itens', to='item.itemrifado')),
                ('rifas_ganhas', models.ManyToManyField(blank=True, related_name='rifas_ganhas', to='rifa.rifa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
