# Generated by Django 5.0.7 on 2024-08-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('rifa', '0009_rifa_arrumado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirado', models.BooleanField(default=False)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('numero_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rifa.numerovendido')),
                ('rifa_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa')),
            ],
        ),
    ]
